# k8s/grafana-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: |
    [paths]
    data = /var/lib/grafana
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    
    [server]
    root_url = http://localhost:3000
    
    [smtp]
    enabled = true
    host = smtp.gmail.com:587
    from_address = ${GF_SMTP_USER}
    from_name = Grafana
    startTLS_policy = MandatoryStartTLS
