# k8s/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  PROMETHEUS_AUTH_TOKEN: "a82d741a9da9732d82f3f404191e6a6e73abef464a4f6a079773503f0331c81c"
  GRAFANA_ADMIN_PASSWORD: "admin123"
  ELASTICSEARCH_PASSWORD: "elastic-password"
