# monitoring/prometheus/prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'task-service'
    static_configs:
      - targets: ['task-service:8000']
    metrics_path: '/metrics'
