# .github/workflows/security.yml
name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install security tools
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety
          
      - name: Run Bandit (Security static code analysis)
        run: |
          bandit -r app/ -f json -o bandit-report.json || true
          
      - name: Run Safety (Check dependencies for vulnerabilities)
        run: |
          safety check --full-report -r requirements.txt || true
          
      - name: Upload security reports
        uses: actions/upload-artifact@v4  # Updated from v2 to v3
        with:
          name: security-reports
          path: bandit-report.json
